# Generated by Django 5.2 on 2025-04-27 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_participation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='start_date',
        ),
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='challenge',
            name='point_value',
            field=models.PositiveIntegerField(default=10, help_text='Points awarded upon completion'),
        ),
        migrations.AddField(
            model_name='participation',
            name='points_awarded',
            field=models.PositiveIntegerField(blank=True, help_text='Points earned at completion', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'challenge')},
        ),
    ]
