# Generated by Django 5.2 on 2025-04-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined_challenges',
            field=models.ManyToManyField(blank=True, related_name='participants', to='challenges.challenge'),
        ),
    ]
