# Generated by Django 5.2 on 2025-04-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='next_goal',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
