# Generated by Django 5.1.5 on 2025-04-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_next_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_fit_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_fit_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
