# Generated by Django 5.2 on 2025-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_google_fit_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="equipment_available",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="fitness_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
    ]
