# Generated by Django 5.2 on 2025-04-27 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_meal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Injury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("neck", "Neck"),
                            ("shoulder", "Shoulder"),
                            ("upper_back", "Upper Back"),
                            ("lower_back", "Lower Back"),
                            ("chest", "Chest"),
                            ("arm", "Arm"),
                            ("elbow", "Elbow"),
                            ("wrist", "Wrist"),
                            ("hip", "Hip"),
                            ("thigh", "Thigh"),
                            ("knee", "Knee"),
                            ("ankle", "Ankle"),
                            ("foot", "Foot"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date_logged", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("recovery_recommendations", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
